import  Head  from "next/head";
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Layout({title, description, children}){
    return(
        <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name={description} content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Head> 
   <meta name="viewport" content="width=device-width, initial-scale=1" /> 
</Head>
      </Head>
      
      
      <main className={styles.main}>
      <div className={styles.div}>
        <h1 className={styles.title}>
          <Link href="/">
         <a>know.ly</a>
          </Link>
        </h1>
        <h3 className={styles.description2}>Conocimiento Diario</h3>
        </div>
          {children}
          </main>

      {/* <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
    )
}

Layout.defaultProps={
    title:"know.ly || Home"

}